---
- name: Playbook com loop
  hosts: docker
  tasks:
    - name: Garantir a instalacao dos pacotes
      apt: name={{ item }} state=present
      with_items:
        - vim
        - nano
        - wget
