---
- name: Playbook com when
  hosts: docker
  tasks:
    - name: testando o arquivo profile
      command: test -f /etc/profile.d/dexter
      register: result
      ignore_errors: yes

    - name: criando arquivo
      shell: echo "export DEXTER_HOME=/etc/dexter" > /etc/profile.d/dexter
      when: result.rc != 0
