---
# tasks file for docker
- name: Garantir a instalacao do Docker
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Incluir o repositorio do Docker-Engine
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Inclusao da chave do repositorio do Docker-Engine
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Instalar o Docker Engine
  apt: name=docker-ce state=present update-cache=yes
